/**
 * Emits the ABIs the web client needs into web/lib/abi.ts, so the frontend and
 * the contracts can never drift. Run after `npm run compile`.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const ARTIFACTS = path.join(ROOT, "artifacts/contracts");
const CONTRACTS = ["WagerBook", "GroupRegistry", "ResolverRegistry", "Treasury", "PlayDollar"];

// Both consumers get the ABIs committed as source. The API used to read
// Hardhat's build output at runtime, which meant the deployed container needed
// a directory that is gitignored — and could silently drift from the contracts.
const TARGETS = [
  { file: path.resolve(ROOT, "../web/lib/abi.ts"), contracts: ["WagerBook", "GroupRegistry", "PlayDollar"] },
  { file: path.resolve(ROOT, "../api/src/abi.ts"), contracts: CONTRACTS },
];

for (const target of TARGETS) {
  const parts = [
    "// Generated by contracts/scripts/export-abi.js — do not edit by hand.",
    "// Regenerate with: cd contracts && npm run export-abi",
    "",
  ];

  for (const name of target.contracts) {
    const file = path.join(ARTIFACTS, `${name}.sol`, `${name}.json`);
    const { abi } = JSON.parse(fs.readFileSync(file, "utf8"));
    const varName = name.charAt(0).toLowerCase() + name.slice(1);
    parts.push(`export const ${varName}Abi = ${JSON.stringify(abi, null, 2)} as const;`);
    parts.push("");
  }

  fs.mkdirSync(path.dirname(target.file), { recursive: true });
  fs.writeFileSync(target.file, parts.join("\n"));
  console.log(`Wrote ${target.file}`);
}
