/**
 * Emits the ABIs the web client needs into web/lib/abi.ts, so the frontend and
 * the contracts can never drift. Run after `npm run compile`.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const ARTIFACTS = path.join(ROOT, "artifacts/contracts");
const OUT = path.resolve(ROOT, "../web/lib/abi.ts");

const CONTRACTS = ["Wager", "WagerFactory", "GroupRegistry"];

const parts = [
  "// Generated by contracts/scripts/export-abi.js — do not edit by hand.",
  "// Regenerate with: cd contracts && npm run export-abi",
  "",
];

for (const name of CONTRACTS) {
  const file = path.join(ARTIFACTS, `${name}.sol`, `${name}.json`);
  const { abi } = JSON.parse(fs.readFileSync(file, "utf8"));
  parts.push(`export const ${name.charAt(0).toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(abi, null, 2)} as const;`);
  parts.push("");
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, parts.join("\n"));
console.log(`Wrote ${OUT}`);
